/**
 * src/routeTree.tsx
 *
 * Hand-authored TanStack Router route tree.
 *
 * The page components under `src/routes` are plain exported components rather
 * than `createFileRoute` modules, so the tree is wired up explicitly here
 * instead of being generated by the file-based routing plugin. Route ids are
 * chosen to match the `from` values used by the page components (e.g. the trip
 * detail page reads params via `from: "/trips/$tripId/"`).
 */

import { createRootRoute, createRoute } from "@tanstack/react-router";
import { RootLayout } from "@/routes/__root";
import { IndexPage } from "@/routes/index";
import { InvitePage } from "@/routes/invite/$token";
import { LoginPage } from "@/routes/login";
import { ScrapsPage } from "@/routes/scraps/index";
import { SignupPage } from "@/routes/signup";
import { TripDetailPage } from "@/routes/trips/$tripId/index";
import { ItineraryPage } from "@/routes/trips/$tripId/itinerary";
import { ScheduleEditPage } from "@/routes/trips/$tripId/schedule-edit";
import { TodoDetailPage } from "@/routes/trips/$tripId/todos/$todoId";
import { TripsPage } from "@/routes/trips/index";

const rootRoute = createRootRoute({
  component: RootLayout,
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  component: IndexPage,
});

const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/login",
  component: LoginPage,
});

const signupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/signup",
  component: SignupPage,
});

const tripsIndexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/trips",
  component: TripsPage,
});

const scrapsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/scraps",
  component: ScrapsPage,
});

const inviteRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/invite/$token",
  component: InvitePage,
});

// Layout route for a single trip; renders its child route via <Outlet />.
const tripRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/trips/$tripId",
});

// Index child -> id "/trips/$tripId/", matching `useParams({ from: ... })`.
const tripDetailIndexRoute = createRoute({
  getParentRoute: () => tripRoute,
  path: "/",
  component: TripDetailPage,
});

const scheduleEditRoute = createRoute({
  getParentRoute: () => tripRoute,
  path: "/schedule-edit",
  component: ScheduleEditPage,
  validateSearch: (search: Record<string, unknown>) => ({
    date: typeof search.date === "string" ? search.date : "",
  }),
});

const itineraryRoute = createRoute({
  getParentRoute: () => tripRoute,
  path: "/itinerary",
  component: ItineraryPage,
});

const todoDetailRoute = createRoute({
  getParentRoute: () => tripRoute,
  path: "/todos/$todoId",
  component: TodoDetailPage,
});

export const routeTree = rootRoute.addChildren([
  indexRoute,
  loginRoute,
  signupRoute,
  tripsIndexRoute,
  scrapsRoute,
  inviteRoute,
  tripRoute.addChildren([tripDetailIndexRoute, scheduleEditRoute, itineraryRoute, todoDetailRoute]),
]);
