/**
 * src/routeTree.tsx
 *
 * Hand-authored TanStack Router route tree.
 *
 * The page components under `src/routes` are plain exported components rather
 * than `createFileRoute` modules, so the tree is wired up explicitly here
 * instead of being generated by the file-based routing plugin. Route ids are
 * chosen to match the `from` values used by the page components (e.g. the trip
 * detail page reads params via `from: "/trips/$tripId/"`).
 */

import { RootLayout } from "@/routes/__root";
import { IndexPage } from "@/routes/index";
import { TripDetailPage } from "@/routes/trips/$tripId/index";
import { TripsPage } from "@/routes/trips/index";
import { createRootRoute, createRoute } from "@tanstack/react-router";

const rootRoute = createRootRoute({
  component: RootLayout,
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/",
  component: IndexPage,
});

const tripsIndexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/trips",
  component: TripsPage,
});

// Layout route for a single trip; renders its child route via <Outlet />.
const tripRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/trips/$tripId",
});

// Index child -> id "/trips/$tripId/", matching `useParams({ from: ... })`.
const tripDetailIndexRoute = createRoute({
  getParentRoute: () => tripRoute,
  path: "/",
  component: TripDetailPage,
});

export const routeTree = rootRoute.addChildren([
  indexRoute,
  tripsIndexRoute,
  tripRoute.addChildren([tripDetailIndexRoute]),
]);
